package com.unicauca.smart_consumption.infrastructure.pattern.mapper;

import com.unicauca.smart_consumption.domain.product.Product;
import com.unicauca.smart_consumption.domain.valueobject.Category;
import com.unicauca.smart_consumption.infrastructure.pattern.dto.CategoryDto;
import com.unicauca.smart_consumption.infrastructure.pattern.dto.ProductPostgresDto;

import org.mapstruct.Mapper;


/**
 * Mapper interface for converting between {@link ProductPostgresDto} and {@link Product}.
 * <p>The implementation of this interface is automatically generated by Map Struct during the build process, ensuring
 * that the mappings are efficient and error-free.</p>
 *
 * @see ProductPostgresDto
 * @see Product
 * @see EntityMapper
 */
@Mapper(componentModel = "spring")
public interface ProductPostgresMapper
    extends EntityMapper<ProductPostgresDto, Product>{

  
}
