package com.unicauca.smart_consumption.infrastructure.pattern.mapper;


import com.unicauca.smart_consumption.domain.user.User;
import com.unicauca.smart_consumption.infrastructure.user.dataproviders.UserJPAEntity;
import org.mapstruct.Mapper;
/**
 * Mapper interface for converting between {@link UserJPAEntity} and {@link User}.
 * <p>The implementation of this interface is automatically generated by Map Struct during the build process, ensuring
 * that the mappings are efficient and error-free.</p>
 *
 * @see UserJPAEntity
 * @see User
 * @see EntityMapper
 *
 *
 * **/
@Mapper(componentModel = "spring")
public interface UserJPAMapper extends EntityMapper<UserJPAEntity, User>{
}
